### ISSUE TITLE
Run Plebnet as TOR Exit code

### ISSUE THREAD

**Issue by andrebreis** [MattSkala/PlebNet#2]

**Comment by andrebreis** [comment]
After #1 , this is done by just flipping the flag of exit node, so run:
``` bash install.sh develop 1 0 ```

right, @MattSkala ?

**Comment by MattSkala** [comment]
That should be it, but I'm not sure how to verify if it's actually running.

**Comment by andrebreis** [comment]
You can confirm you are earning MB's on your wallet
